const shopping=['Bread','Milk','Cheese'];
console.log(shopping);
let rollNo=[34,4,6,8,67,99];
console.log(rollNo);
rollNo.push(100);
console.log(rollNo);
rollNo.pop();
console.log(rollNo);

const flower=['Rose','jasmine','Lotus','sun Flower'];
console.log(flower);

flower.push('Lily');
console.log(flower);

flower.pop();
console.log(flower);

flower.shift();
console.log(flower);

flower.unshift('Tulip');
console.log(flower); 